version: '3'

services:
  factory_server:
    image: lesserfish/gccg-base:latest
    ports:
      - "29101:29101"
      - "29100:29100"
      - "29200-29299:29200-29299"
    healthcheck:
      test: ["CMD", "netcat", "-z", "-w", "5", "mtg.lesser.fish", "29101"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    working_dir: /mtg
    command: bash -c "cp -nr /server/* /mtg/ && ./ccg_server --load factory-server.triggers mtg.xml"
    volumes: 
      - /mtg:/mtg

  meta_server:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    depends_on:
      factory_server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "netcat", "-z", "-w", "5", "mtg.lesser.fish", "29100"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    working_dir: /mtg
    command: ./ccg_server --load meta-server.triggers mtg.xml
    volumes: 
      - /mtg:/mtg


  # Tables: 
  
  table_1a:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - /mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    working_dir: /mtg
    command: ./ccg_server --server localhost --port 29200 --players 1 --bet 0 --load server.triggers mtg.xml

  table_1b:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - /mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    working_dir: /mtg
    command: ./ccg_server --server localhost --port 29201 --players 1 --bet 0 --load server.triggers mtg.xml


  table_2a:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - /mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    working_dir: /mtg
    command: ./ccg_server --server localhost --port 29202 --players 2 --bet 0 --load server.triggers mtg.xml

  table_2b:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - /mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    working_dir: /mtg
    command: ./ccg_server --server localhost --port 29203 --players 2 --bet 0 --load server.triggers mtg.xml


  table_3:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - /mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    working_dir: /mtg
    command: ./ccg_server --server localhost --port 29204 --players 3 --bet 0 --load server.triggers mtg.xml

  table_4:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - /mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    working_dir: /mtg
    command: ./ccg_server --server localhost --port 29205 --players 4 --bet 0 --load server.triggers mtg.xml

  table_bet_2a:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - /mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    working_dir: /mtg
    command: ./ccg_server --server localhost --port 29206 --players 2 --bet 5 --load server.triggers mtg.xml

  table_bet_2b:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - /mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    working_dir: /mtg
    command: ./ccg_server --server localhost --port 29207 --players 2 --bet 10 --load server.triggers mtg.xml

