version: '3'
services:
  factory-server:
    image: lesserfish/gccg-base:latest
    ports:
      - "29101:29101"
    networks:
      - gccg-network
    healthcheck:
      test: ["netcat", "-z", "-w", "5", "localhost", "20101"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    command: ./Server factory-mtg

  meta-server:
    image: lesserfish/gccg-base:latest
    ports:
      - "29100:29100"
    networks:
      - gccg-network
    depends_on:
      factory-server:
        condition: service_healthy
    healthcheck:
      test: ["netcat", "-z", "-w", "5", "localhost", "20100"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

    command: ./Server meta-mtg

networks:
  gccg-network:
    driver: bridge
