version: '3'

services:
  factory_server:
    image: lesserfish/gccg-base:latest
    ports:
      - "29101:29101"
      - "29100:29100"
      - "29200-29299:29200-29299"
    healthcheck:
      test: ["CMD", "netcat", "-z", "-w", "5", "localhost", "29101"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    command: ./Server factory-mtg
    volumes: 
      - ./factory_data:/server/save

  meta_server:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    depends_on:
      factory_server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "netcat", "-z", "-w", "5", "localhost", "29100"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    command: ./Server meta-mtg
    volumes: 
      - ./meta_data:/server/save


  # Tables: 
  
  table_1:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    command: ./Server --server localhost --port 29200 --players 1 --bet 0 mtg

