version: '3'

services:
  factory_server:
    image: lesserfish/gccg-base:latest
    ports:
      - "29101:29101"
      - "29100:29100"
      - "29200-29299:29200-29299"
    healthcheck:
      test: ["CMD", "netcat", "-z", "-w", "5", "localhost", "29101"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    command: bash -c "cp -nr /server/* /mtg/ && /mtg/Server factory-mtg"
    volumes: 
      - ./mtg:/mtg

  meta_server:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    depends_on:
      factory_server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "netcat", "-z", "-w", "5", "localhost", "29100"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    command: /mtg/Server meta-mtg
    volumes: 
      - ./mtg:/mtg


  # Tables: 
  
  table_1:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - ./mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    command: /mtg/Server --server localhost --port 29200 --players 2 --bet 0 mtg


  table_2:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - ./mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    command: /mtg/Server --server localhost --port 29201 --players 2 --bet 5 mtg

  table_3:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - ./mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    command: /mtg/Server --server localhost --port 29202 --players 2 --bet 10 mtg

  table_4:
    image: lesserfish/gccg-base:latest
    network_mode: "service:factory_server"
    volumes: 
      - ./mtg:/mtg
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    command: /mtg/Server --server localhost --port 29203 --players 2 --bet 20 mtg
