version: '3'

services:
  factory_server:
    image: lesserfish/gccg-base:latest
    ports:
      - "29101:29101"
    healthcheck:
      test: ["CMD", "netcat", "-z", "-w", "5", "localhost", "29101"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    command: ./Server factory-mtg
    volumes: 
      - ./factory_data:/server/save

  meta_server:
    image: lesserfish/gccg-base:latest
    ports:
      - "29100:29100"
    depends_on:
      factory_server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "netcat", "-z", "-w", "5", "localhost", "29100"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    command: ./Server meta-mtg
    volumes: 
      - ./meta_data:/server/save


  # Tables: 
  
  table_1:
    image: lesserfish/gccg-base:latest
    ports:
      - 29200:29200
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    command: ./Server --server meta_server --port 29200 --players 2 --bet 0 mtg

  table_2:
    image: lesserfish/gccg-base:latest
    ports:
      - 29201:29201
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    command: ./Server --server meta_server --port 29201 --players 2 --bet 5 mtg

  table_3:
    image: lesserfish/gccg-base:latest
    ports:
      - 29202:29202
    depends_on:
      meta_server:
        condition: service_healthy
    restart: always
    command: ./Server --server meta_server --port 29202 --players 2 --bet 10 mtg
