FROM ubuntu:22.04
WORKDIR /server

RUN dpkg --add-architecture i386

# Update package lists and install dependencies
RUN apt update \
    && apt install -y \
        wget \
        libsdl1.2debian:i386 \
        libsdl-image1.2:i386 \
        libsdl-ttf2.0-0:i386 \
        libsdl-mixer1.2:i386 \
        libsdl-net1.2:i386

# Download and extract gccg-core
RUN wget -P /server/ http://gccg.sourceforge.net/modules/gccg-core-1.0.10.tgz \
    && tar zxvf /server/gccg-core-1.0.10.tgz

# Install gccg and MTG
RUN ./gccg_package install client fonts linux-i386 mtg server mtg-server
COPY scripts/meta-server.triggers scripts/
COPY scripts/meta-server.functions scripts/
