FROM ubuntu:22.04
WORKDIR /server

RUN dpkg --add-architecture i386

# Update package lists and install dependencies
RUN apt update \
    && apt install -y \
        wget \
        netcat \
        libsdl1.2debian \
        libsdl-image1.2 \
        libsdl-ttf2.0-0 \
        libsdl-mixer1.2 \
        libsdl-net1.2

# Download and extract gccg-core

COPY Content/* .
RUN /bin/bash -c 'for file in *.tgz; do tar -xf "$file"; done'

